# Load Library

In [2]:
import torch
import torch.nn as nn

# Create input and Output variable

In [3]:
X = torch.tensor([
    [1.0],
    [2.0],
    [3.0],
    [4.0]
])

y = torch.tensor([
    [2.0],
    [4.0],
    [6.0],
    [8.0]
])
X, y

(tensor([[1.],
         [2.],
         [3.],
         [4.]]),
 tensor([[2.],
         [4.],
         [6.],
         [8.]]))

# Create Linear Regression model only one input and one output

y = mx + c

In [4]:
model = nn.Linear(in_features=1, out_features=1)

# Define Loss function

In [5]:
criterion = nn.MSELoss()

# Define optimizer with Learning rate

In [6]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Training Loop

In [7]:
for epoch in range(1000):
    y_pred = model(X) # predict : Forward pass
    loss = criterion(y_pred, y) # calculate loss
    optimizer.zero_grad() # clear previous gradients
    loss.backward() # backpropagation: compute gradients
    optimizer.step() # update weights using gradients

    if (epoch +1)%100 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item():.4f}')


Epoch 100, Loss: 0.0044
Epoch 200, Loss: 0.0024
Epoch 300, Loss: 0.0013
Epoch 400, Loss: 0.0007
Epoch 500, Loss: 0.0004
Epoch 600, Loss: 0.0002
Epoch 700, Loss: 0.0001
Epoch 800, Loss: 0.0001
Epoch 900, Loss: 0.0000
Epoch 1000, Loss: 0.0000


# After Training, print the learned weight and bias

In [10]:
params = list(model.parameters())
print(f'Learned weight: {params[0].item():.4f}, Learned bias: {params[1].item():.4f}')

Learned weight: 1.9963, Learned bias: 0.0108


In [11]:
params

[Parameter containing:
 tensor([[1.9963]], requires_grad=True),
 Parameter containing:
 tensor([0.0108], requires_grad=True)]

In [12]:
model.state_dict()  # model parameters

OrderedDict([('weight', tensor([[1.9963]])), ('bias', tensor([0.0108]))])