In [3]:
import torch
import torch.nn as nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import torch.nn.functional as F

In [29]:
X = torch.tensor([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
y = torch.tensor([[0.], [1.], [1.], [0.]])
X, y

(tensor([[0., 0.],
         [0., 1.],
         [1., 0.],
         [1., 1.]]),
 tensor([[0.],
         [1.],
         [1.],
         [0.]]))

In [30]:
X = torch.tensor([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
Y = torch.tensor([[0.], [1.], [1.], [0.]])
X,y

(tensor([[0., 0.],
         [0., 1.],
         [1., 0.],
         [1., 1.]]),
 tensor([[0.],
         [1.],
         [1.],
         [0.]]))

In [62]:
class XORNet(nn.Module):
    def __init__(self):
        super(XORNet, self).__init__()
        self.fc1 = nn.Linear(2,4)
        self.fc2 = nn.Linear(4,8)
        self.fc3 = nn.Linear(8,4)
        self.out = nn.Linear(4,1)
    
    def forward(self, x):
        x = self.fc1(x)
        x = torch.sigmoid(x)
        x = torch.relu(self.fc2(x))
        x = torch.relu(self.fc3(x))
        x = torch.sigmoid(self.out(x))
        return x



In [65]:
model = XORNet()
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [66]:
for epoch in range(5000):
    output = model(X)
    loss = criterion(output, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

Epoch 100, Loss: 0.6932
Epoch 200, Loss: 0.6932
Epoch 300, Loss: 0.6932
Epoch 400, Loss: 0.6932
Epoch 500, Loss: 0.6932
Epoch 600, Loss: 0.6932
Epoch 700, Loss: 0.6932
Epoch 800, Loss: 0.6932
Epoch 900, Loss: 0.6932
Epoch 1000, Loss: 0.6932
Epoch 1100, Loss: 0.6932
Epoch 1200, Loss: 0.6932
Epoch 1300, Loss: 0.6932
Epoch 1400, Loss: 0.6932
Epoch 1500, Loss: 0.6932
Epoch 1600, Loss: 0.6932
Epoch 1700, Loss: 0.6932
Epoch 1800, Loss: 0.6932
Epoch 1900, Loss: 0.6932
Epoch 2000, Loss: 0.6932
Epoch 2100, Loss: 0.6932
Epoch 2200, Loss: 0.6932
Epoch 2300, Loss: 0.6932
Epoch 2400, Loss: 0.6932
Epoch 2500, Loss: 0.6932
Epoch 2600, Loss: 0.6932
Epoch 2700, Loss: 0.6932
Epoch 2800, Loss: 0.6932
Epoch 2900, Loss: 0.6932
Epoch 3000, Loss: 0.6932
Epoch 3100, Loss: 0.6932
Epoch 3200, Loss: 0.6932
Epoch 3300, Loss: 0.6932
Epoch 3400, Loss: 0.6932
Epoch 3500, Loss: 0.6932
Epoch 3600, Loss: 0.6932
Epoch 3700, Loss: 0.6932
Epoch 3800, Loss: 0.6932
Epoch 3900, Loss: 0.6932
Epoch 4000, Loss: 0.6932
Epoch 410

In [67]:
with torch.no_grad():
    predict = model(X).round()
    print("prediction: ", predict)

prediction:  tensor([[0.],
        [0.],
        [1.],
        [1.]])
